language: android
android:
  components:
    # The BuildTools version
    - build-tools-25.0.2

    #The SDK version
    - android-25

    #extra android support
    - extra-android-support
before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
