language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    # The BuildTools version
    - build-tools-25.0.2
    #The SDK version
    - android-25
    #extra android support
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
jdk:
  - oraclejdk8

before_install:
    - chmod +x gradlew

