language: android
android:
  components:

    - platform-tools-25.0.5
    # The BuildTools version
    - build-tools-25.0.2
    #The SDK version
    - android-25
    #extra android support
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
jdk:
  - oraclejdk8

before_install:
    - chmod +x gradlew

