language: android
android:
  components:

    - platform-tools-25.0.5

    # The BuildTools version
    - build-tools-25.0.2

    #The SDK version
    - android-25

    #extra android support
    - extra-android-support

    - extra-android-m2repository

before_install:

script:
    - adb devices
    - ./gradlew assembleDebug
    - ./gradlew :testDebug

