language: android
android:
  components:
    - tools
    - tools
    - platform-tools-25.0.3
    # The BuildTools version
    - build-tools-25.0.3
    #The SDK version
    - android-25
    #extra android support
    #- extra
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
jdk:
  - oraclejdk8

before_install:
    #- chmod +x gradlew
    
script:
# force init of adb way before any Gradle task that uses ADB; prevents a timeout error that skips emulators of android-24
  - adb devices
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
# run all the local unit tests of app module
  - ./gradlew :testDebug

